# Generated by Django 3.0.2 on 2020-03-18 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='TodoList',
        ),
    ]
