# Generated by Django 3.0.2 on 2020-03-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_auto_20200324_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='author',
            new_name='created_by',
        ),
    ]
